defaults: &defaults
  region:     'ap-northeast-1'
  endpoint:   'sqs.ap-northeast-1.amazonaws.com'
  queue_url:  'https://sqs.ap-northeast-1.amazonaws.com/633565662126/Apocalypse'
  queue_name: 'Apocalypse'
